# سيقوم سير العمل هذا ببناء تطبيق node.js ودفعه إلى تطبيق Azure Web App عند دفع التزام إلى فرعك الافتراضي.
#
# يفترض سير العمل هذا أنك قمت ب٧لسيل بإنشاء تطبيق الويب Azure App Service الممممستهدف.
        اسم اسم:تطبيق العقدةتطبيق العقدةاسم اسم:تطبيق العقدةتطبيق العقدة
#
# لتكوين سير العمل هذا:
#
#1. كم بتنزيل من تف طريف النشر لببيبك طابق طابق تطبيق Azure Web App الخاس بك. يمكنك تنزيل هذا الملف من صفحة نظرة عامة على تطبيق الويب الخاص بك في بوابة أزور.
# لمزيد من المعلومات: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
#2. قم بمشاشا س ر في المسيتعدة الخاس بـ ك باسم AZURE_WEBAPP_PUBLISH_PROFILE، تم كم بسق مهتويات ملف تعريف النشر قميمة للسر.
# للحصول على تعليمات حول كيفية الحصول على ملف تعريف النشر، راجع: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
#3. قم بتجير قيمة AZURE_WEBAPP_NAME. اغتيريا، كم بتجير متغيرات البية AZURE_WEBAPP_PACKAGE_PATH وNODE_VERSION ادناه.
#
# لمزيد من المن المنتمات جهتف لـ أزور: https://github.com/Azure/Actions
# لمزيد من المن المن هل تبعت الويب Azure Deploy: https://github.com/Azure/webapps-deploy
      علىعلىعلىعلىعلىعلىعلىعلى

علىعلى
 ماسر مزامة AZURE_WEBAPP_PACKAGEماسر مزامة AZURE_WEBAPP_PACKAGE :
علىعلى ىعلى ىعلى ىعلى [ ماسر مزامة AZURE_WEBAPP_PACKAGEماسر مزامة AZURE_WEBAPP_PACKAGE"الرئيسي" ]
        عنو٧ن URL اللٮ٧سص بـ عنو٧نالعمل_الإرسال عنو٧ن URL اللٮ٧سص بـ عنو٧نالعمل_الإرسال عنو٧ن URL اللٮ٧سص بـ عنو٧نالعمل_الإرسال عنو٧ن URL الللٮ٧سص بـ عنو٧نالع�      عنو٧ن URL اللٮ٧سص بـ عنو٧نالعمل_الإرسال عنو٧ن URL الللٮ٧سص بـ عنو٧نالعمل_الإرسال      عنو٧ن URL الللٮ٧سص بـ عنو٧نالعمل_الإرسال      عنو٧ن URL اللللٮ٧سص بـ عنو٧نالعمل_الإرسال:

البيئةبيئة:
  اسم طَبْق الْوَيب الأزرقْوَيب الأزرق: اسم التطبيق الخاص بك    # اضبط هذا على اسم التطبيق الخاص بك
  مصار هزة AZURE_WEBAPPمصار هزة AZURE_WEBAPPمصار هزة AZURE_WEBAPPمصار هزة AZURE_WEBAPP: '.'      # اضبط هذا على المسار إلى مشروع تطبيق الويب الخاص بك، ويتم تعيينه افتراضيًا على جذر المستودع
  إصدار العقدةإصدار العقدة: '20.x'                # اضبط هذا على إصدار العقدة المراد استخدامه

الأذوناتأذوناتأذوناتأذونات:
  محتوياتمحتوياتتوياتمحتويقراءةتوياتمحتوياتتوياتمحتويقراءة: قراءة

وظائفففف:
  بناءاءاءاء:
    يعمل علىيعمل علىأوبونتو-الأحدثأوبونتو-الأحدثمل علىيعمل علىأوبونتو-الأحدثأوبونتو-الأحدث
    خطواتخطواتواتخطواتواتخطواتواتخطوات:
    - الاستخداماتالإجراءات/checkout@v4: الإجراءات/checkout@v4

    - اسمممم: إعداد Node.js
      الاستخداماتاستخداماالإجراءات/setup-node@v4  الإجراءات/setup-node@v4: الإجراءات/setup-node@v4
      مع مع:
        إصدار العقدة إصدار العقدة    إصدار العقدة    إصدار العقدة: ${{ env.NODE_VERSION }}
        كاشيات كاشيات كاش'npm'  كاشيات كاشيات    كاش'npm': 'npm'

    - اسماسم تثبيت npm وبنائه واختبارهماسم تثبيت npm وبنائه واختباره
      الركضالركضركضالركض: |
        طبطبي٪ npm طبطبي٪ npmطبطبي٪ npm طبطبي٪ npm      طبطبي٪ npm طبطبي٪ npmطبطبي٪ npm  طبطبي٪ npm
        npm run build --if-presentnpm run build --if-present    npm run build --if-presentnpm run build --if-present
        اختبار تشغيل NPM --إذا-حاضر اختبار تشغيل NPM --إذا-حاضر اختبار تشغيل NPM --إذا-حاضر اختبار تشغيل NPM --إذا-حاضر  npm run test --if-presentnpm run test --if-present      npm run test --if-presentnpm run test --if-present

    - اسمتحميل قطعة أثرية لمهمة النشرتحميل قطعة أثرية لمهمة النشر
      الاستخدامات الاستخدامات الاستخدامات الاالإجراءات/upload-artifact@v4  الاستخدامات الاستخدامات  الاستخدامات  الاالإجراءات/upload-artifact@v4: الإجراءات/upload-artifact@v4
      معمع معمعمعمع  معمع:
        اسم اسم اسم اسمتطبيق العقدةطبيق العقدة: تطبيق العقدةطبيق العقدة
        طريق طريق طريق طريق: .

  نشرر:
    الأذوناتأذوناتالأذوناتأذوناتأذوناتأذوناتالأذوناتأذونات:
      محتويات محتوياتتويات  محتويات: لا أحد
    يعمل علىيعمل علىمل علىيعمل على: أوبونتو-الأحدث
    احتياجاتاحبناءبناءاحتياجاتبناء: بناء
    بيئةئةئةئة:
      اسمم اسمم"التنمية": "التنمية"
      عنو٧ن خطوات.نشر-إلى-تطبيق الويب.المخرجات.عِنو٧ن رابط لتۇٴبِيق الَّوبعنو٧ن خطوات.نشر-إلى-تطبيق الويب.المخرجات.عِنو٧ن رابط لتۇٴبِيق الَّوبعنو٧ن خطوات.نشر-إلى-تطبيق الويب.المخرجات.عِنو٧ن رابط لتۇٴبِيق الَّوبعنو٧ن خطوات.نشر-إلى-تطبيق الويب.المخرجات.عِنو٧ن رابط لتۇٴبِيق الَّوب : ${{ خطوات.نشر-إلى-تطبيق الويب.المخرجات.عِنو٧ن رابط لتۇٴبِيق الَّوب }}

    خطواتواتواتواتواتواتواتواتواتواتتواتواتواتواتواتواتوات:
    - اسممتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناءممتنزيل القطعة الأثرية من مهممتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناءممتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناءتنزيل القطعة الأثرية من مهمة البناء
      الاستخداماتالاستخداماتاستخداماتالاستخدامات: الإجراءات/download-artifact@v4
      مع مع مع مع مع:
        اسم اسم:تطبيق العقدةتطبيق العقدةاسم اسم:تطبيق العقدةتطبيق العقدة

    - اسمم: 'النشر على Azure WebApp'
      هويةنشر على تطبيق الويب: نشر على تطبيق الويب
      الاستخداماتأزرق سماوي/webapps-deploy@v2: أزرق سماوي/webapps-deploy@v2
      مع:
        اسم التطبيق: ${{ env.AZURE_WEBAPP_NAME }}
        نشر الملف الشخصي: ${{ أسرار.من ظريف نشر ظاق AZURE_WEBAPP }}
        حزمة: ${{ ماسر مزمة AZURE_WEBAPP_PACKAGE }}
